function draw_system_block(cfg, figDir, palette)
% 绘制 2PSK 数字通信系统结构框图。

fig = figure('Name', '2PSK system block', 'Color', 'w', 'Position', [80 80 1180 420]);
axes('Position', [0 0 1 1]);
axis off; hold on; xlim([0 1]); ylim([0 1]);
text(0.5, 0.86, '2PSK 数字通信系统结构框图', ...
    'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
    'FontName', cfg.fontName, 'FontSize', 18, ...
    'FontWeight', 'bold', 'Color', palette.ink);

labels = {'随机 bit', '极性映射\newline0/1 -> -1/+1', '2PSK 调制\newline乘载波', ...
    'AWGN 信道', '相干相关\newline积分器', '过零判决', 'BER 统计'};
x = linspace(0.035, 0.855, numel(labels));
y = 0.38 * ones(size(x));
w = 0.105; h = 0.25;
fills = [palette.pale; [0.90 0.96 1.00]; [0.88 0.98 0.97]; ...
    [1.00 0.95 0.86]; [0.90 0.96 1.00]; [0.88 0.98 0.97]; palette.pale];

for i = 1:numel(labels)
    rectangle('Position', [x(i) y(i) w h], 'Curvature', 0.08, ...
        'FaceColor', fills(i,:), 'EdgeColor', palette.line, 'LineWidth', 1.2);
    text(x(i)+w/2, y(i)+h/2, labels{i}, 'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', 'FontName', cfg.fontName, ...
        'FontSize', 11.5, 'Color', palette.ink, 'Interpreter', 'tex');
    if i < numel(labels)
        text((x(i)+w+x(i+1))/2, y(i)+h/2, '→', ...
            'HorizontalAlignment', 'center', 'VerticalAlignment', 'middle', ...
            'FontName', 'Arial', 'FontSize', 19, 'FontWeight', 'bold', ...
            'Color', palette.muted);
    end
end
text(0.5, 0.18, '核心链路：发送端相位调制 -> 加性白噪声 -> 相干解调 -> 误码率性能评估', ...
    'HorizontalAlignment', 'center', 'FontName', cfg.fontName, ...
    'FontSize', 13, 'Color', palette.muted);

exportgraphics(fig, fullfile(figDir, '00_system_block.png'), ...
    'Resolution', cfg.exportDpi, 'BackgroundColor', 'white');
if isfield(cfg, 'saveFigFiles') && cfg.saveFigFiles
    savefig(fig, fullfile(figDir, '00_system_block.fig'));
end
close(fig);
end
